version: '3.5'

services:
    ctfd:
        build:
            context: .
            args:
                - WORKDIR=/opt/CTFd
        user: root
        restart: always
        ports:
            - 8000:8000
        environment:
            - SECRET_KEY=random_this
            - UPLOAD_FOLDER=/var/uploads
            - WORKERS=4
            - LOG_FOLDER=/var/log/CTFd
            - ACCESS_LOG=/var/log/CTFd/access.log
            - ERROR_LOG=/var/log/CTFd/error.log
            - PROBLEM_DOCKER_RUN_FOLDER=/tmp/owl/run # 题目容器运行的文件夹，保证与下方 volumes 中的一致
            - DATABASE_URL=sqlite:////var/db/ctfd.db # sync db
        volumes:
            - .data:/opt/CTFd/.data # sync cache
            - .data/db:/var/db # sync db
            - .data/CTFd/logs:/var/log/CTFd
            - .data/CTFd/uploads:/var/uploads
            - ./challenges:/opt/CTFd/CTFd/plugins/ctfd-owl/source # Mount the challenges
            - /tmp/owl/run:/tmp/owl/run # DIND 和容器的映射目录和 PROBLEM_DOCKER_RUN_FOLDER 一致，保证题目创建时不会出现找不到题目容器的映射目录等情况
            - /var/run/docker.sock:/var/run/docker.sock # 保证通过容器的 docker.sock 能操作宿主机的 docker.sock
        depends_on:
            - frpc
        networks:
            default:
            internal:
            frp:
                ipv4_address: 10.1.0.5

    frps:
        image: spaceskynet/bitnsc-frp
        # you can build image by yourself if you want.
        #build: ./frp
        restart: always
        volumes:
            - ./frp/conf:/conf/
        expose:
            - 80
        ports:
            - 20000-20099:20000-20099
        entrypoint:
            - /app/frps
            - -c
            - /conf/frps.ini
        networks:
            default:
            frp:
                ipv4_address: 10.1.0.3

    frpc:
        image: spaceskynet/bitnsc-frp
        # you can build image by yourself if you want.
        #build: ./frp
        restart: always
        volumes:
            - ./frp/conf:/conf/
        expose:
            - 7400
        entrypoint:
            - /app/frpc
            - -c
            - /conf/frpc.ini
        depends_on:
            - frps
        networks:
            frp:
                ipv4_address: 10.1.0.4
            frp_containers:

networks:
    default:
        name: 'bitnsc_default'
    internal:
        name: 'bitnsc_internal'
        internal: true
    frp:
        name: 'bitnsc_frp'
        driver: bridge
        ipam:
            config:
                - subnet: 10.1.0.0/16
    frp_containers:
        name: 'bitnsc_frp_containers'
        driver: bridge
        ipam:
            config:
                - subnet: 10.2.0.0/16
